import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

import { domainLocator, linkLocator } from '../../descriptions/common';

const show = { resource: ['linkOpenGraph'] };

/** All 66 OpenGraph tag names Short.io accepts, alphabetical by key (the digest gives no display names). */
const OPENGRAPH_KEYS: INodePropertyOptions[] = [
	{ name: 'Audio', value: 'audio' },
	{ name: 'book:author', value: 'book:author' },
	{ name: 'book:isbn', value: 'book:isbn' },
	{ name: 'book:release_date', value: 'book:release_date' },
	{ name: 'book:tag', value: 'book:tag' },
	{ name: 'Description', value: 'description' },
	{ name: 'Determiner', value: 'determiner' },
	{ name: 'Image', value: 'image' },
	{ name: 'image:alt', value: 'image:alt' },
	{ name: 'image:height', value: 'image:height' },
	{ name: 'image:secure_url', value: 'image:secure_url' },
	{ name: 'image:type', value: 'image:type' },
	{ name: 'image:url', value: 'image:url' },
	{ name: 'image:width', value: 'image:width' },
	{ name: 'Locale', value: 'locale' },
	{ name: 'locale:alternate', value: 'locale:alternate' },
	{ name: 'music:album', value: 'music:album' },
	{ name: 'music:album:disc', value: 'music:album:disc' },
	{ name: 'music:album:track', value: 'music:album:track' },
	{ name: 'music:creator', value: 'music:creator' },
	{ name: 'music:duration', value: 'music:duration' },
	{ name: 'music:musician', value: 'music:musician' },
	{ name: 'music:release_date', value: 'music:release_date' },
	{ name: 'music:song', value: 'music:song' },
	{ name: 'music:song:disc', value: 'music:song:disc' },
	{ name: 'music:song:track', value: 'music:song:track' },
	{ name: 'profile:first_name', value: 'profile:first_name' },
	{ name: 'profile:gender', value: 'profile:gender' },
	{ name: 'profile:last_name', value: 'profile:last_name' },
	{ name: 'profile:username', value: 'profile:username' },
	{ name: 'Site_name', value: 'site_name' },
	{ name: 'Title', value: 'title' },
	{ name: 'twitter:app:country', value: 'twitter:app:country' },
	{ name: 'twitter:app:ID:googleplay', value: 'twitter:app:id:googleplay' },
	{ name: 'twitter:app:ID:ipad', value: 'twitter:app:id:ipad' },
	{ name: 'twitter:app:ID:iphone', value: 'twitter:app:id:iphone' },
	{ name: 'twitter:app:name:googleplay', value: 'twitter:app:name:googleplay' },
	{ name: 'twitter:app:name:ipad', value: 'twitter:app:name:ipad' },
	{ name: 'twitter:app:name:iphone', value: 'twitter:app:name:iphone' },
	{ name: 'twitter:app:url:googleplay', value: 'twitter:app:url:googleplay' },
	{ name: 'twitter:app:url:ipad', value: 'twitter:app:url:ipad' },
	{ name: 'twitter:app:url:iphone', value: 'twitter:app:url:iphone' },
	{ name: 'twitter:card', value: 'twitter:card' },
	{ name: 'twitter:creator', value: 'twitter:creator' },
	{ name: 'twitter:creator:ID', value: 'twitter:creator:id' },
	{ name: 'twitter:description', value: 'twitter:description' },
	{ name: 'twitter:image', value: 'twitter:image' },
	{ name: 'twitter:image:alt', value: 'twitter:image:alt' },
	{ name: 'twitter:player', value: 'twitter:player' },
	{ name: 'twitter:player:height', value: 'twitter:player:height' },
	{ name: 'twitter:player:stream', value: 'twitter:player:stream' },
	{ name: 'twitter:player:width', value: 'twitter:player:width' },
	{ name: 'twitter:site', value: 'twitter:site' },
	{ name: 'twitter:site:ID', value: 'twitter:site:id' },
	{ name: 'twitter:title', value: 'twitter:title' },
	{ name: 'Type', value: 'type' },
	{ name: 'Url', value: 'url' },
	{ name: 'Video', value: 'video' },
	{ name: 'video:actor', value: 'video:actor' },
	{ name: 'video:actor:role', value: 'video:actor:role' },
	{ name: 'video:director', value: 'video:director' },
	{ name: 'video:duration', value: 'video:duration' },
	{ name: 'video:release_date', value: 'video:release_date' },
	{ name: 'video:series', value: 'video:series' },
	{ name: 'video:tag', value: 'video:tag' },
	{ name: 'video:writer', value: 'video:writer' },
];

export const linkOpenGraphDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Get',
				value: 'get',
				description: "Get a link's OpenGraph properties",
				action: 'Get open graph properties for a link',
			},
			{
				name: 'Set',
				value: 'set',
				description: "Set a link's OpenGraph properties",
				action: 'Set open graph properties for a link',
			},
		],
		default: 'get',
	},
	domainLocator(show),
	linkLocator(show),
	{
		displayName: 'Properties',
		name: 'properties',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		placeholder: 'Add Property',
		default: {},
		displayOptions: { show: { ...show, operation: ['set'] } },
		options: [
			{
				displayName: 'Property',
				name: 'property',
				values: [
					{
						displayName: 'Key',
						name: 'key',
						type: 'options',
						options: OPENGRAPH_KEYS,
						default: 'title',
						description: 'The OpenGraph tag name',
					},
					{
						displayName: 'Value',
						name: 'value',
						type: 'string',
						default: '',
						description: 'The OpenGraph tag value',
					},
				],
			},
		],
	},
];
